name: orvex_pay
description: Official Flutter SDK for OrvexPay. Integrate crypto payments into your Flutter apps with a native, secure, and customizable modal.
version: 0.1.0
homepage: https://github.com/OrvexPay/OrvexPay-Flutter-SDK
repository: https://github.com/OrvexPay/OrvexPay-Flutter-SDK
issue_tracker: https://github.com/OrvexPay/OrvexPay-Flutter-SDK/issues
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  qr_flutter: ^4.1.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
